version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: lint
          command: npm run lint
  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
  update_upstream:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: npm ci
      - run: git submodule foreach git pull origin master
      - run: npm run update
      - run: npm run build
      - run:
          name: "git config"
          command: |
            git config credential.helper "cache --timeout=120"
            git config user.email "tracker-definitions@nothing.com"
            git config user.name "Deployment Bot"
            ssh-add -D
      - run: git add .
      - run: "git commit -a -m 'fix: update from upstream'"
      - run: git push -q https://${GH_TOKEN}@github.com/TypeCtrl/tracker-definitions.git master

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * 0"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - update_upstream


