export const definition: any = {
  site: 'sceneaccess',
  name: 'sceneaccess',
  language: 'en-us',
  links: ['https://sceneaccess.eu/'],
  caps: {
    categories: {
      '1': 'PC/ISO',
      '2': 'PC/0day',
      '3': 'PC/Games',
      '4': 'Movies',
      '5': 'Console/PS3',
      '7': 'Movies',
      '8': 'Movies/SD',
      '11': 'TV',
      '12': 'XXX/XviD',
      '13': 'Audio/MP3',
      '14': 'Other/Misc',
      '15': 'Audio/Video',
      '17': 'TV/SD',
      '20': 'Console/PSP',
      '21': 'Other/Misc',
      '22': 'Movies',
      '23': 'Console/Xbox360',
      '26': 'TV',
      '27': 'TV/HD',
      '28': 'Console/Wii',
      '29': 'PC/Mac',
      '30': 'Movies/Foreign',
      '31': 'Movies/Foreign',
      '32': 'Movies/Foreign',
      '33': 'TV/Foreign',
      '34': 'TV/Foreign',
      '35': 'XXX/x264',
      '36': 'XXX',
      '37': 'XXX',
      '38': 'Audio',
      '40': 'Audio/Lossless',
      '41': 'Movies/HD',
      '42': 'Movies/SD',
      '43': 'Movies/SD',
      '44': 'TV/SD',
      '45': 'TV/HD',
    },
  },
  login: {
    path: '/login',
    method: 'form',
    inputs: {
      username: '{{ .Config.username }}',
      password: '{{ .Config.password }}',
    },
    error: [{ message: { selector: '#login_box_desc' } }],
    test: { path: '/inbox' },
  },
  search: {
    path: '/all',
    inputs: { $raw: 'search={{ .Query.Keywords }}&method=2' },
    rows: { selector: 'tr.tt_row' },
    fields: {
      category: {
        selector: 'td.ttr_type a[href^="?cat="]',
        attribute: 'href',
        filters: [{ name: 'regexp', args: '\\?cat=(\\d+)' }],
      },
      title: { selector: 'td.ttr_name a', attribute: 'title' },
      details: { selector: 'td.ttr_name a', attribute: 'href' },
      comments: { selector: 'td.ttr_name a', attribute: 'href' },
      download: { selector: 'td.td_dl a', attribute: 'href' },
      size: {
        selector: 'td.ttr_size',
        filters: [{ name: 'regexp', args: '(\\d*.\\d*\\s..).*' }],
      },
      date: { selector: 'td.ttr_added' },
      seeders: { selector: 'td.ttr_seeders' },
      leechers: { selector: 'td.ttr_leechers' },
    },
  },
};
