export const definition: any = {
  site: 'torrentsectorcrew',
  name: 'Torrent Sector Crew',
  description: 'A German general tracker',
  language: 'de-de',
  links: ['https://tsctracker.net/'],
  caps: {
    categories: {
      '4': 'PC/Games',
      '5': 'Movies/3D',
      '6': 'Audio',
      '9': 'Other',
      '19': 'Movies/SD',
      '20': 'Movies/DVD',
      '22': 'PC/0day',
      '24': 'Audio/Audiobook',
      '28': 'Books',
      '29': 'Audio/Video',
      '36': 'Movies/HD',
      '37': 'Console/NDS',
      '38': 'Audio/Audiobook',
      '42': 'TV/Sport',
      '43': 'Movies/BluRay',
      '48': 'PC/Mac',
      '50': 'Console/Xbox',
      '54': 'Movies/HD',
      '55': 'Movies/HD',
      '58': 'Console/PS4',
      '64': 'XXX',
      '65': 'PC/Phone-Android',
      '66': 'TV/SD',
      '68': 'TV',
      '69': 'TV/HD',
      '72': 'TV/Foreign',
      '75': 'TV/Documentary',
      '76': 'TV/Documentary',
      '77': 'TV/Documentary',
      '78': 'TV/Documentary',
      '82': 'Audio',
      '83': 'PC/Phone-IOS',
      '103': 'Other',
      '104': 'Audio',
      '107': 'PC/0day',
      '108': 'TV',
      '109': 'PC',
      '111': 'Movies',
      '112': 'TV/Anime',
      '113': 'TV/Documentary',
      '114': 'TV/Documentary',
      '115': 'PC/Mac',
      '116': 'Other',
      '117': 'Other',
      '119': 'Movies',
      '120': 'Movies/Foreign',
      '121': 'Movies/HD',
    },
  },
  settings: [
    { name: 'pin', type: 'text', label: 'Pin' },
    { name: 'username', type: 'text', label: 'Username' },
    { name: 'password', type: 'password', label: 'Password' },
  ],
  login: {
    path: 'landing.php',
    method: 'form',
    form: 'form',
    inputs: {
      username: '{{ .Config.username }}',
      password: '{{ .Config.password }}',
      pin: '{{ .Config.pin }}',
    },
    error: [{ selector: '#login_box_desc' }],
    test: { path: 'my.php' },
  },
  ratio: {
    path: '/my.php',
    selector: 'td.navi_top:contains("Deine Ratio:")',
    filters: [
      { name: 'replace', args: ['Deine Ratio: ', ''] },
      { name: 'replace', args: ['.', ''] },
      { name: 'replace', args: [',', '.'] },
    ],
  },
  search: {
    path: 'browse.php',
    inputs: {
      $raw: '{{range .Categories}}c{{.}}=1&{{end}}',
      search: '{{ .Query.Keywords }}',
      incldead: '1',
      orderby: 'added',
      sort: 'desc',
    },
    rows: {
      selector:
        'h2 +p + br + table.tablebrowse > tbody > tr[style="height: 45px;"], tr:contains("Weiter") > td > table.tablebrowse > tbody > tr[style="height: 45px;"]',
    },
    fields: {
      title: {
        selector: 'a[title][href^="details.php"]',
        attribute: 'title',
      },
      category: {
        selector: 'a[href*="cat="]',
        attribute: 'href',
        filters: [{ name: 'querystring', args: 'cat' }],
      },
      comments: { selector: 'a[href*="&tocomm="]', attribute: 'href' },
      download: {
        selector: 'a[href^="download_ssl.php"]',
        attribute: 'href',
      },
      files: { selector: 'td:nth-child(3)' },
      grabs: {
        selector: 'td:nth-child(9)',
        filters: [{ name: 'replace', args: ['-mal', ''] }],
      },
      size: {
        selector: 'td:nth-child(6)',
        filters: [{ name: 'replace', args: ['.', ''] }, { name: 'replace', args: [',', '.'] }],
      },
      seeders: {
        selector: 'td:nth-child(7)',
        filters: [{ name: 'regexp', args: '(\\d+)' }],
      },
      leechers: {
        selector: 'td:nth-child(8)',
        filters: [{ name: 'regexp', args: '(\\d+)' }],
      },
      date: {
        selector: 'td:nth-child(5)',
        remove: 'br',
        filters: [{ name: 'dateparse', args: '02.01.200615:04:05' }],
      },
      downloadvolumefactor: {
        case: {
          'font:contains("[OnlyUpload]")': '0',
          'font:contains("[-40 Download]")': '0.6',
          '*': '1',
        },
      },
      uploadvolumefactor: { case: { '*': '1' } },
    },
  },
};
