import { TopLevel } from '../definition-interface';
export const definition: TopLevel = {
  site: 'torrentsyndikat',
  name: 'Torrent-Syndikat',
  description: 'A German general tracker',
  language: 'de-DE',
  encoding: 'UTF-8',
  links: ['https://torrent-syndikat.org/'],
  caps: {
    categories: {
      '2': 'PC',
      '3': 'Movies/BluRay',
      '4': 'PC/Mac',
      '5': 'PC/Phone-Other',
      '6': 'PC',
      '7': 'Console/Wii',
      '8': 'Console/PSP',
      '9': 'Movies/HD',
      '10': 'Movies/SD',
      '11': 'Movies/Other',
      '12': 'PC/Games',
      '13': 'PC',
      '15': 'TV/SD',
      '16': 'TV/HD',
      '17': 'Books',
      '18': 'Audio/Audiobook',
      '20': 'Movies/HD',
      '21': 'Movies/DVD',
      '22': 'Movies/3D',
      '23': 'TV/HD',
      '24': 'Audio/Lossless',
      '25': 'Audio/MP3',
      '26': 'Audio',
      '27': 'TV/SD',
      '28': 'TV/Documentary',
      '29': 'TV/Documentary',
      '30': 'TV/Sport',
      '31': 'Movies/Other',
      '32': 'Console/Xbox',
      '33': 'Audio/Video',
      '35': 'Audio/Other',
      '36': 'TV/Foreign',
      '37': 'Movies/Foreign',
      '39': 'Other',
      '40': 'TV/Anime',
      '41': 'Console/NDS',
      '42': 'Movies/HD',
      '44': 'TV/HD',
    },
  },
  settings: [{ name: 'cookie', type: 'text', label: 'Cookie' }],
  login: {
    method: 'cookie',
    inputs: { cookie: '{{ .Config.cookie }}' },
    test: { path: '/ucp.php?action=default' },
  },
  ratio: {
    path: '/browse.php',
    selector: 'i[title="Gesamtratio"] ~ span',
  },
  search: {
    path: '/browse.php?do=search',
    inputs: {
      $raw: '{{range .Categories}}c{{.}}=1&{{end}}',
      search: '{{ .Query.Keywords }}',
      searchin: 'title',
      incldead: 1,
      rel_type: 0,
    },
    rows: {
      selector: 'table.torrent_table > tbody > tr:not(:has(td.colhead))',
    },
    fields: {
      title: {
        selector: 'a[title][href^="details.php"]',
        attribute: 'title',
      },
      category: {
        selector: 'a[href^="browse.php?cat="]',
        attribute: 'href',
        filters: [{ name: 'querystring', args: 'cat' }],
      },
      comments: {
        selector: 'a[title][href^="details.php"]',
        attribute: 'href',
      },
      download: {
        selector: 'a[href^="download.php"]',
        attribute: 'href',
      },
      size: { selector: 'td:nth-child(6)' },
      seeders: { selector: 'td:nth-child(8)' },
      leechers: { selector: 'td:nth-child(9)' },
      date: {
        selector: 'span.torrent_details',
        remove: 'i, a',
        filters: [
          { name: 'replace', args: ['Heute', 'Today'] },
          { name: 'replace', args: ['Gestern', 'Yesterday'] },
          { name: 'replace', args: [' von', ''] },
        ],
      },
    },
  },
};
