import { TopLevel } from '../definition-interface';
export const definition: TopLevel = {
  site: 'xthor',
  name: 'Xthor',
  language: 'fr-fr',
  links: ['https://xthor.bz/'],
  caps: {
    categories: {
      '1': 'Movies/BluRay',
      '2': 'Movies/BluRay',
      '3': 'Movies/3D',
      '4': 'Movies/HD',
      '5': 'Movies/HD',
      '6': 'Movies/SD',
      '7': 'Movies/SD',
      '8': 'Movies/DVD',
      '9': 'Movies/Other',
      '12': 'TV/Documentary',
      '13': 'TV',
      '14': 'TV/SD',
      '15': 'TV/HD',
      '16': 'TV/Other',
      '17': 'TV/Other',
      '21': 'PC',
      '22': 'PC/Mac',
      '23': 'PC/Phone-Other',
      '24': 'Books',
      '25': 'PC/Games',
      '26': 'Console',
      '27': 'Console',
      '28': 'Console/Wii',
      '29': 'Console/NDS',
      '30': 'TV',
      '31': 'Movies',
      '32': 'TV/Anime',
      '33': 'TV/Other',
      '34': 'TV/Sport',
      '94': 'Movies',
      '95': 'Movies',
      '96': 'Books/Magazines',
      '98': 'TV/Other',
      '99': 'Books',
      '100': 'Movies/HD',
      '101': 'TV/Anime',
      '102': 'Books/Comics',
      '103': 'Books',
      '104': 'TV',
    },
  },
  login: {
    path: '/takelogin.php',
    method: 'post',
    form: 'form',
    inputs: {
      username: '{{ .Config.username }}',
      password: '{{ .Config.password }}',
      submitme: 'X',
      returnto: '/',
    },
    test: { path: '/usercp.php' },
  },
  search: {
    path: 'browse.php',
    inputs: {
      $raw: '{{range .Categories}}c{{.}}=1&{{end}}',
      searchin: 'title',
      incldead: 0,
      group: 0,
      search: '{{ .Query.Keywords }}',
    },
    rows: {
      selector:
        'div.article > table:nth-child(11) > tbody > tr:has(a[href^="download.php?torrent="])',
    },
    fields: {
      title: { selector: 'a[href^="details.php?id="]' },
      category: {
        selector: 'a[href^="browse.php?cat="]',
        attribute: 'href',
        filters: [{ name: 'querystring', args: 'cat' }],
      },
      comments: {
        selector: 'a[href^="details.php?id="]',
        attribute: 'href',
      },
      download: {
        selector: 'a[href^="download.php?torrent="]',
        attribute: 'href',
      },
      size: {
        selector: 'td:nth-child(6)',
        filters: [
          { name: 'replace', args: ['Gio', 'gb'] },
          { name: 'replace', args: ['Mio', 'mb'] },
          { name: 'replace', args: ['Kio', 'kb'] },
        ],
      },
      seeders: { selector: 'td:nth-child(8)' },
      leechers: { selector: 'td:nth-child(9)' },
      date: {
        selector: 'td:nth-child(2) > a',
        attribute: 'onmouseover',
        filters: [
          { name: 'replace', args: [' ', ''] },
          { name: 'regexp', args: 'Ajouté le: </u>(?:<?)(.+?)</b>' },
        ],
      },
      downloadvolumefactor: {
        case: { 'img[src*="/freedownload.gif"]': '0', '*': '1' },
      },
      uploadvolumefactor: { case: { '*': '1' } },
      grabs: { selector: 'td:nth-child(7) > a' },
    },
  },
};
