import { TrackerDefinition } from '../definition-interface';

export const definition: TrackerDefinition = {
  site: '4thd',
  name: '4thD',
  description: '4th Dimension is a Private Torrent Tracker for MOVIES / TV / GENERAL',
  language: 'en-US',
  encoding: 'UTF-8',
  type: 'private',
  links: ['https://4thd.xyz/'],
  caps: {
    categorymappings: [
      { id: '38', cat: 'Movies', 'Movie Pack': null },
      { id: '36', cat: 'Movies', 'Movies/Classic Films': null },
      { id: '13', cat: 'Movies', 'Movies/Documentary': null },
      { id: '21', cat: 'Movies/Foreign', 'Movies/Foreign': null },
      { id: '27', cat: 'Movies/HD', MoviesHD: null },
      { id: '29', cat: 'Movies/SD', 'Movies/SD': null },
      { id: '26', cat: 'Movies/SD', 'Movies/XviD': null },
      { id: '41', cat: 'TV/Foreign', 'Foreign tv': null },
      { id: '40', cat: 'TV', 'Mini-Series': null },
      { id: '43', cat: 'TV/HD', 'TV H265': null },
      { id: '42', cat: 'TV', 'TV Movie': null },
      { id: '4', cat: 'TV/HD', 'TV/HD-x720': null },
      { id: '14', cat: 'TV', 'TV/Packs': null },
      { id: '2', cat: 'TV/SD', 'TV/SD MP4/mkv': null },
      { id: '31', cat: 'TV/SD', 'TV/XviD': null },
      { id: '18', cat: 'PC/Games', 'Games/PC': null },
      { id: '12', cat: 'Audio/Lossless', 'Music/FLAC': null },
      { id: '15', cat: 'Audio/MP3', 'Music/MP3': null },
      { id: '37', cat: 'Audio', Radio: null },
      { id: '9', cat: 'PC/0day', 'Apps/PC': null },
      { id: '34', cat: 'Audio/Audiobook', Audiobooks: null },
      { id: '25', cat: 'Books/Ebook', eBooks: null },
    ],
    modes: {
      search: ['q'],
      'tv-search': ['q', 'season', 'ep'],
      'movie-search': ['q'],
    },
  },
  login: {
    path: 'login.php',
    method: 'form',
    form: 'form#loginform',
    inputs: {
      username: '{{ .Config.username }}',
      password: '{{ .Config.password }}',
      keeplogged: 1,
    },
    error: [{ selector: 'form#loginform .warning' }],
    test: { path: 'index.php', selector: 'a[href^="logout.php?auth="]' },
  },
  search: {
    paths: [{ path: 'torrents.php' }],
    inputs: {
      $raw: '{{range .Categories}}filter_cat[{{.}}]=1&{{end}}',
      order_by: 'time',
      order_way: 'desc',
      filter_freeleech: 0,
      title: '{{ .Keywords }}',
      search_type: 1,
      taglist: '',
      tags_type: 0,
    },
    rows: { selector: 'table#torrent_table > tbody > tr.torrent' },
    fields: {
      category: {
        selector: 'td.cats_col div a',
        attribute: 'href',
        filters: [{ name: 'regexp', args: '\\[(\\d+)\\]' }],
      },
      title: { selector: 'a[href^="torrents.php?id="]' },
      details: {
        selector: 'a[href^="torrents.php?id="]',
        attribute: 'href',
      },
      download: {
        selector: 'a[href^="torrents.php?action=download&id="]',
        attribute: 'href',
      },
      description: { selector: 'div.tags' },
      banner: {
        selector: 'td:nth-child(2) script',
        optional: true,
        filters: [
          { name: 'regexp', args: 'src=(.*?)>' },
          { name: 're_replace', args: ['\\\\', ''] },
        ],
      },
      files: { selector: 'td:nth-child(3)' },
      date: { selector: 'td:nth-child(5)' },
      size: { selector: 'td:nth-child(6)' },
      grabs: { selector: 'td:nth-child(7)' },
      seeders: { selector: 'td:nth-child(8)' },
      leechers: { selector: 'td:nth-child(9)' },
      downloadvolumefactor: {
        case: { 'img[src$="/freedownload.gif"]': 0, '*': 1 },
      },
      uploadvolumefactor: { case: { '*': 1 } },
    },
  },
  source: 'jackett',
};
