import { TrackerDefinition } from '../definition-interface';

export const definition: TrackerDefinition = {
  site: 'sukebei-pantsu',
  name: 'Sukebei-pantsu',
  description: 'Sukebei-pantsu is a Public site dedicated to Adult Asian content',
  language: 'en-EN',
  type: 'public',
  encoding: 'UTF-8',
  links: ['https://sukebei.nyaa.net/'],
  legacylinks: ['https://sukebei.pantsu.cat/'],
  settings: [
    {
      name: 'cat-id',
      type: 'select',
      label: 'Category',
      default: '_',
      options: {
        '11': 'Art - Anime',
        '12': 'Art - Doujinshi',
        '13': 'Art - Games',
        '14': 'Art - Manga',
        '15': 'Art - Pictures',
        '21': 'Real Life - Photobooks and Pictures',
        '22': 'Real Life - Videos',
        _: 'All categories',
        '1_': 'Art',
        '2_': 'Real Life',
      },
    },
    {
      name: 'sort',
      type: 'select',
      label: 'Sort requested from site',
      default: '2',
      options: { '1': 'title', '2': 'created', '4': 'size', '5': 'seeders' },
    },
    {
      name: 'type',
      type: 'select',
      label: 'Order requested from site',
      default: 'false',
      options: { false: 'desc', true: 'asc' },
    },
  ],
  caps: {
    categorymappings: [
      { id: '1_', cat: 'XXX', desc: 'Adult Art' },
      { id: '11', cat: 'XXX', desc: 'Adult Anime' },
      { id: '12', cat: 'XXX', desc: 'Doujinshi' },
      { id: '13', cat: 'XXX', desc: 'Adult Games' },
      { id: '14', cat: 'XXX', desc: 'Adult Manga' },
      { id: '15', cat: 'XXX', desc: 'Adult Pictures' },
      { id: '2_', cat: 'XXX', desc: 'Adult Real Life' },
      { id: '21', cat: 'XXX', desc: 'Adult Photobooks and Pictures' },
      { id: '22', cat: 'XXX', desc: 'Adult Videos' },
      { id: '23', cat: 'XXX', desc: 'Unknown' },
      { id: '24', cat: 'XXX', desc: 'Unknown' },
      { id: '25', cat: 'XXX', desc: 'Unknown' },
      { id: '26', cat: 'XXX', desc: 'Unknown' },
      { id: '27', cat: 'XXX', desc: 'Unknown' },
      { id: '28', cat: 'XXX', desc: 'Unknown' },
      { id: '29', cat: 'XXX', desc: 'Unknown' },
      { id: '210', cat: 'XXX', desc: 'Unknown' },
      { id: '3_', cat: 'XXX', desc: 'Unknown' },
      { id: '31', cat: 'XXX', desc: 'Unknown' },
      { id: '32', cat: 'XXX', desc: 'Unknown' },
      { id: '33', cat: 'XXX', desc: 'Unknown' },
      { id: '34', cat: 'XXX', desc: 'Unknown' },
      { id: '35', cat: 'XXX', desc: 'Unknown' },
      { id: '36', cat: 'XXX', desc: 'Unknown' },
      { id: '37', cat: 'XXX', desc: 'Unknown' },
      { id: '38', cat: 'XXX', desc: 'Unknown' },
      { id: '39', cat: 'XXX', desc: 'Unknown' },
      { id: '310', cat: 'XXX', desc: 'Unknown' },
      { id: '311', cat: 'XXX', desc: 'Unknown' },
      { id: '312', cat: 'XXX', desc: 'Unknown' },
      { id: '313', cat: 'XXX', desc: 'Unknown' },
      { id: '314', cat: 'XXX', desc: 'Unknown' },
      { id: '315', cat: 'XXX', desc: 'Unknown' },
      { id: '316', cat: 'XXX', desc: 'Unknown' },
      { id: '317', cat: 'XXX', desc: 'Unknown' },
      { id: '318', cat: 'XXX', desc: 'Unknown' },
      { id: '319', cat: 'XXX', desc: 'Unknown' },
      { id: '320', cat: 'XXX', desc: 'Unknown' },
      { id: '4_', cat: 'XXX', desc: 'Unknown' },
      { id: '41', cat: 'XXX', desc: 'Unknown' },
      { id: '42', cat: 'XXX', desc: 'Unknown' },
      { id: '43', cat: 'XXX', desc: 'Unknown' },
      { id: '44', cat: 'XXX', desc: 'Unknown' },
      { id: '45', cat: 'XXX', desc: 'Unknown' },
      { id: '46', cat: 'XXX', desc: 'Unknown' },
      { id: '47', cat: 'XXX', desc: 'Unknown' },
      { id: '48', cat: 'XXX', desc: 'Unknown' },
      { id: '49', cat: 'XXX', desc: 'Unknown' },
      { id: '410', cat: 'XXX', desc: 'Unknown' },
      { id: '411', cat: 'XXX', desc: 'Unknown' },
      { id: '412', cat: 'XXX', desc: 'Unknown' },
      { id: '413', cat: 'XXX', desc: 'Unknown' },
      { id: '414', cat: 'XXX', desc: 'Unknown' },
      { id: '415', cat: 'XXX', desc: 'Unknown' },
      { id: '416', cat: 'XXX', desc: 'Unknown' },
      { id: '417', cat: 'XXX', desc: 'Unknown' },
      { id: '418', cat: 'XXX', desc: 'Unknown' },
      { id: '419', cat: 'XXX', desc: 'Unknown' },
      { id: '420', cat: 'XXX', desc: 'Unknown' },
      { id: '5_', cat: 'XXX', desc: 'Unknown' },
      { id: '51', cat: 'XXX', desc: 'Unknown' },
      { id: '52', cat: 'XXX', desc: 'Unknown' },
      { id: '53', cat: 'XXX', desc: 'Unknown' },
      { id: '54', cat: 'XXX', desc: 'Unknown' },
      { id: '55', cat: 'XXX', desc: 'Unknown' },
      { id: '56', cat: 'XXX', desc: 'Unknown' },
      { id: '57', cat: 'XXX', desc: 'Unknown' },
      { id: '58', cat: 'XXX', desc: 'Unknown' },
      { id: '59', cat: 'XXX', desc: 'Unknown' },
      { id: '510', cat: 'XXX', desc: 'Unknown' },
      { id: '511', cat: 'XXX', desc: 'Unknown' },
      { id: '512', cat: 'XXX', desc: 'Unknown' },
      { id: '513', cat: 'XXX', desc: 'Unknown' },
      { id: '514', cat: 'XXX', desc: 'Unknown' },
      { id: '515', cat: 'XXX', desc: 'Unknown' },
      { id: '516', cat: 'XXX', desc: 'Unknown' },
      { id: '517', cat: 'XXX', desc: 'Unknown' },
      { id: '518', cat: 'XXX', desc: 'Unknown' },
      { id: '519', cat: 'XXX', desc: 'Unknown' },
      { id: '520', cat: 'XXX', desc: 'Unknown' },
      { id: '6_', cat: 'XXX', desc: 'Unknown' },
      { id: '61', cat: 'XXX', desc: 'Unknown' },
      { id: '62', cat: 'XXX', desc: 'Unknown' },
      { id: '63', cat: 'XXX', desc: 'Unknown' },
      { id: '64', cat: 'XXX', desc: 'Unknown' },
      { id: '65', cat: 'XXX', desc: 'Unknown' },
      { id: '66', cat: 'XXX', desc: 'Unknown' },
      { id: '67', cat: 'XXX', desc: 'Unknown' },
      { id: '68', cat: 'XXX', desc: 'Unknown' },
      { id: '69', cat: 'XXX', desc: 'Unknown' },
      { id: '610', cat: 'XXX', desc: 'Unknown' },
      { id: '611', cat: 'XXX', desc: 'Unknown' },
      { id: '612', cat: 'XXX', desc: 'Unknown' },
      { id: '613', cat: 'XXX', desc: 'Unknown' },
      { id: '615', cat: 'XXX', desc: 'Unknown' },
      { id: '616', cat: 'XXX', desc: 'Unknown' },
      { id: '617', cat: 'XXX', desc: 'Unknown' },
      { id: '618', cat: 'XXX', desc: 'Unknown' },
      { id: '619', cat: 'XXX', desc: 'Unknown' },
      { id: '620', cat: 'XXX', desc: 'Unknown' },
    ],
    modes: { search: ['q'], 'tv-search': ['q'] },
  },
  search: {
    paths: [{ path: 'search' }],
    inputs: {
      q: '{{ .Keywords }}',
      c: '{{ .Config.cat-id }}',
      s: 0,
      sort: '{{ .Config.sort }}',
      order: '{{ .Config.type }}',
    },
    rows: { selector: 'tr.torrent-info' },
    fields: {
      title: { selector: 'td.tr-name a' },
      category: {
        selector: 'td:nth-child(1) a',
        attribute: 'href',
        filters: [{ name: 'split', args: ['=', -1] }],
      },
      details: { selector: 'td.tr-name a', attribute: 'href' },
      download: {
        selector: 'a[title="Magnet Link"]',
        attribute: 'href',
      },
      seeders: { selector: 'td.tr-se', optional: true },
      leechers: { selector: 'td.tr-le', optional: true },
      grabs: { selector: 'td.tr-dl', optional: true },
      date: {
        selector: 'td.date-short',
        filters: [{ name: 'dateparse', args: '2006-01-02T15:04:05Z' }],
      },
      size: {
        selector: 'td.tr-size',
        filters: [{ name: 'replace', args: ['Unknown', '0'] }],
      },
      downloadvolumefactor: { text: 0 },
      uploadvolumefactor: { text: 1 },
    },
  },
  source: 'jackett',
};
